### ISSUE TITLE
build post users for oauth

### ISSUE THREAD

**Issue by duranangela** [duranangela/neighborhood#26]
Build endpoint for post to users

**Comment by sdmalek44** [comment]
POST /api/v1/users

the frontend will send the payload they get back from google oauth through this post request 
the controller will do a database lookup for a user with that specific googleToken and email address which should both be made to be unique. If it finds a user it will return the user id through the body of the response. (either the actual user_id or unique key that every user will get upon creation). The front end can use this user_id to make any fetch call for user information and can store it in the session/cookie however they want to maintain it to keep the user logged in.
